//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universitati
    {
        public int Id { get; set; }
        public string NameUniv { get; set; }
        public string City { get; set; }
        public int Code { get; set; }
    }
}
